---
- hosts: local
  connection: local
  become: false

  tasks:
  - name: Stop pre-existing container for the app
    command: docker stop greeting
    ignore_errors: yes
    
  - name: Remove pre-existing container for the app
    command: docker rm greeting
    ignore_errors: yes
    
  - name: Remove pre-existing image for the app
    command: docker rmi gouthamshiv/greeting:latest
    ignore_errors: yes
    
  - name: Build docker image using artifact
    command: docker build -t gouthamshiv/greeting:latest .
    args:
      chdir: /opt/workspace

  - name: Docker login
    command: docker login -u gouthamshiv -p $DKRLOGIN
    
  - name: Push image to docker-hub
    command: docker push gouthamshiv/greeting:latest

- hosts: docker_host
  become: false
  
  tasks:
  - name: Stop pre-existing container for the app
    command: docker stop greeting
    ignore_errors: yes
    
  - name: Remove pre-existing container for the app
    command: docker rm greeting
    ignore_errors: yes
    
  - name: Remove pre-existing image for the app
    command: docker rmi gouthamshiv/greeting:latest
    ignore_errors: yes

  - name: Pull latest image and start container
    command: docker run -d --name greeting -p 8888:8080 gouthamshiv/greeting:latest
    ignore_errors: yes