---
- hosts: local
  connection: local
  become: false

  tasks:
  - name: Stop pre-existing container for the app
    command: docker stop greeting
    ignore_errors: yes
    
  - name: Remove pre-existing container for the app
    command: docker rm greeting
    ignore_errors: yes
    
  - name: Remove pre-existing image for the app
    command: docker rmi gouthamshiv/greeting:latest
    ignore_errors: yes
    
  - name: Build docker image using artifact
    command: docker build -t gouthamshiv/greeting:latest .
    args:
      chdir: /opt/workspace

  - name: Create container using above image
    command: docker run -d --name greeting -p 8888:8080 gouthamshiv/greeting:latest